#pragma once

namespace irc
{
	enum ServerNotifyCodes
	{
		ERR_PASSWDMISMATCH = 464,
		ERR_NOTREGISTERED = 451,
		ERR_ALREADYREGISTERED = 462,
		ERR_UNKNOWN_COMMAND = 421,
		ERR_NOSUCHNICK = 401,
		ERR_NOSUCHCHANNEL = 403,
		ERR_NOTONCHANNEL = 442,
		ERR_USERNOTINCHANNEL = 441,
		ERR_NOPRIVILEGES = 481,
		ERR_CHANOPRIVSNEEDED = 482,
		RPL_INVITING = 341,
		RPL_NAMREPLY = 353,
		RPL_ENDOFNAMES = 366,
		RPL_WELCOME = 001
	};
}