#pragma once

namespace irc
{
	enum ServerNotifyCodes
	{
		ERR_CHANOPRIVSNEEDED	= 482,
		ERR_NOPRIVILEGES		= 481,
		ERR_BADCHANMASK			= 476,
		ERR_BADCHANNELKEY		= 475,
		ERR_INVITEONLYCHAN		= 473,
		ERR_UNKNOWNMODE			= 472,
		ERR_CHANNELISFULL		= 471,
		ERR_KEYSET				= 467,
		ERR_PASSWDMISMATCH		= 464,
		ERR_ALREADYREGISTERED	= 462,
		ERR_NEEDMOREPARAMS		= 461,
		ERR_NOTREGISTERED		= 451,
		ERR_USERONCHANNEL		= 443,
		ERR_NOTONCHANNEL		= 442,
		ERR_USERNOTINCHANNEL	= 441,
		ERR_NICKNAMEINUSE		= 433,
		ERR_ERRONEUSNICKNAME	= 432,
		ERR_UNKNOWN_COMMAND		= 421,
		ERR_NOSUCHCHANNEL		= 403,
		ERR_NOSUCHNICK			= 401,
		RPL_ENDOFNAMES			= 366,
		RPL_NAMREPLY			= 353,
		RPL_INVITING 			= 341,
		RPL_CHANNELMODEIS		= 324,
		RPL_WELCOME				= 001
	};
}